### ISSUE TITLE
Missing "BBB" on Figure 8.21

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#1047]
In class this week I noticed that the B's are missing from the 3rd row of illustration 8.21. This is what is in the book:

![image](https://github.com/user-attachments/assets/19040e13-d91a-4785-a7b4-3bcb0cf1366b)

This is the correct image is in #297 

![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/8fa646ee-bb58-4506-a604-9409f8899bfd)

@zee-em since this and #981 are just "text" elements in the illustrations I could perhaps make these changes myself? What do you think?

**Comment by zee-em** [comment]
I've fixed this one, uploaded to notion and PNG & Procreate files to Google drive... here's the new image. Hopefully the spacing of the Bs is ok. I remember this one was the bbbane of my existence 
![Figure_8-22](https://github.com/user-attachments/assets/af9b5f7d-e1dd-4e5d-973d-712c8aaf68a3)

**Comment by shiffman** [comment]
Hi @zee-em so adding the three B's into the image seems to have moved the A's and B's around in the bottom two rows. The lines are all in the correct places, but the following rules are not being applied correctly:

1. An `A` appears centered below a horizontal line.
2. A `B` appears centered below a blank space.

See the original image for an exact version:

![image](https://github.com/user-attachments/assets/64038c1c-0d48-4dfa-92a6-375d8e8ce99e)

The bottom row from what we had before you made the change was correct (well, the letters are slightly out of place but I think well within reason given it's hand drawn illustration.)

![image](https://github.com/user-attachments/assets/ff3ed215-7885-463d-bf85-3dfddb16c478)

But in the new version you just added the A's and B's are in weird definitely inplaces.

![image](https://github.com/user-attachments/assets/9b66464e-f0f5-41e9-83fd-9ec279fd25ef)

The letters in the third row are also now in incorrect positions, the spacing should be perfectly even in each row.

![image](https://github.com/user-attachments/assets/59f5939b-9a31-4f8e-bde4-25d508522ae9)

Let me know if this makes sense!

**Comment by shiffman** [comment]
This has now been corrected by moving the letters around manually in the PNG.

**Comment by shiffman** [comment]
And new image is in #1115

**Comment by shiffman** [comment]
Leaving open as a reminder since the original illustration was not fixed.
